name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: devops
          port: 8888
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/devops-lab/My_WebSite/
            git pull origin main
            sudo cp -r * /var/www/solo_project/
            sudo systemctl reload nginx
